"""This File Contains headers as constants which will be used everywhere"""


class TableHeaders:
    """This Class Contains table headers for output"""

    ID = "{} Id"
    MESSAGE = "{} Messgae"
    CREATED_DATE = "Created Date"
    STARTING_DATE = "Starting Date"
    NO_OF_DAYS = "No of Days"
    STATUS = "Status"
    YEAR = "Year"
    MONTH = "Month"
    AMOUNT = "Amount"
    PAY_DATE = "Pay Date"
    NAME = "Name"
    PHONE = "Phone"
    EMAIL = "E-Mail"
    EXPERTISE = "Expertise"
    ADDRESS = "Address"
    GENDER = "Gender"
    LEAVE_DATE = "Leave Date"
    RAISED_BY = "Raised By"
    EXPERIENCE = "Experience"
